### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [chuong/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by chuong** [comment]
I just made a commit to add meta tag viewport. It looks like this improves text display on my phone.
However the link "This isn't enough, I need more" doesn't work well in mobile mode.

**Comment by BillyMassey** [comment]
I just checked out your splurty app on my iPhone and it seemed to work exactly as expected.  There’s a chance it just happened to show the same quote a few times, but if you keep clicking it, it should work.  I’d suggest keep moving through the course and start building out the nomster app.

Keep up the awesome work coding!
